"use client";
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button"
import WeatherCard from './components/WeatherCard';
import fetchWeatherData from '../../libs/fetchWeatherData';
import { WeatherData } from './types/WeatherData';
import { CopilotPopup } from "@copilotkit/react-ui";
import { useCopilotAction } from "@copilotkit/react-core"; 

const HomePage = () => {
  const [location, setLocation] = useState('');
  const [weatherData, setWeatherData] = useState<WeatherData | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setLocation(event.target.value);
  };

  const handleSearch = async () => {
    try {
      const data = await fetchWeatherData(location);
      if (data) {
        setWeatherData(data);
        setError(null);
      } else {
        setError('Failed to fetch weather data. Please try again.');
      }
    } catch (error) {
      console.error('Error fetching weather data:', error);
      setError('An error occurred. Please try again.');
    }
  };

  useCopilotAction({
    name: "fetchWeather",
    description: "Fetches weather data for a given location",
    parameters: [
      {
        name: "location",
        type: "string",
        description: "The city, state, or country for which to fetch weather data",
        required: true,
      },
    ],
    handler: async ({ location }) => {
      try {
        const data = await fetchWeatherData(location);
        if (data) {
          setWeatherData(data);
          setError(null);
        } else {
          setError('Failed to fetch weather data. Please try again.');
        }
      } catch (error) {
        console.error('Error fetching weather data:', error);
        setError('An error occurred. Please try again.');
      }
    },
    render: "Fetching weather data...",
  });

  return (
    <div className="container">
      <Head>
          <head>Weather - Next App</head>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <Image
          src='https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2575&q=80'
          layout='fill'
          alt="background_img"
          className='object-cover'
        />
      <h1 className="text-3xl font-bold text-center">Weather App 🌥️</h1>
      <div className="flex flex-col justify-center items-center mt-10">
        <Input type="text" placeholder="Enter a location" value={location} onChange={handleInputChange} className='w-1/2 h-20' />
        <Button onClick={handleSearch}  className='w- mt-6'>Search</Button>
      </div>
      {error && <p className="text-red-500">{error}</p>}
      {weatherData && <WeatherCard weatherData={weatherData} />}
      <CopilotPopup
        instructions={"You are assisting the user as best as you can. Ansewr in the best way possible given the data you have."}
        labels={{
          title: "Popup Assistant",
          initial: "Need any help?",
        }}
      />
    </div>
  );
};

export default HomePage;